export enum AsElementType {
  Section = "section",
  Div = "div",
  Article = "article",
  Aside = "aside",
  Footer = "footer",
  Header = "header",
  Main = "main",
  H1 = "h1",
  H2 = "h2",
  H3 = "h3",
  H4 = "h4",
  H5 = "h5",
  H6 = "h6",
}
