import "./globals.css";
import Navigation from "@/components/Navigation/Navigation";
import ThemeSwitcher from "@/components/ThemeSwitcher/ThemeSwitcher";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <ThemeProvider>
          <div className="flex flex-wrap items-center relative justify-between z-10">
            <Navigation />
            <ThemeSwitcher />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
