// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  luxury_call_to_action: dynamic(() => import("./LuxuryCallToAction")),
  luxury_fragrance_list: dynamic(() => import("./LuxuryFragranceList")),
  luxury_hero: dynamic(() => import("./LuxuryHero")),
  luxury_product_feature: dynamic(() => import("./LuxuryProductFeature")),
  luxury_scroll_text: dynamic(() => import("./LuxuryScrollText")),
  luxury_video: dynamic(() => import("./LuxuryVideo")),
};
